### ISSUE TITLE
Unsaved uncertainty annotations are not correctly deleted.

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#111]
Deleting an existing annotation fails server-wise. The following existing uncertainty annotation is present in
the initial websocket response:
```
"{"ana":"https://providedh.ehum.psnc.pl/api/projects/2/taxonomy/#imprecision","locus":"value","degree":null,"cert":"medium","resp":"#annotator-2","match":null,"target":"#utensil-1","xml:id":"certainty-2","assertedValue":"oven","desc":"","saved":false,"deleted":false}"
```

The following request is sent to delete the said annotation:
```
{"method":"modify","payload":[{"element_type":"certainty","method":"DELETE","edited_element_id":"certainty-2"}]}
```

The server logs the following problem:
```
web_1            | 2020-07-13 13:40:04,133 - INFO - consumers - Get request from user: 'jancho' with content: '{"method":"modify","payload":[{"element_type":"certainty","method":"DELETE","edited_element_id":"certainty-2"}]}'
web_1            | 2020-07-13 13:40:04,143 - ERROR - consumers - Send response to user: 'jancho' with content: '{"status": 500, "message": "Unhandled exception.", "body_content": null}'
web_1            | Traceback (most recent call last):
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/consumers.py", line 174, in receive
web_1            |     self.__request_handler.modify_file(operations)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/request_handler.py", line 61, in modify_file
web_1            |     self.__delete_certainty(operation)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/request_handler.py", line 488, in __delete_certainty
web_1            |     self.__db_handler.delete_certainty(certainty_xml_id)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/db_handler.py", line 155, in delete_certainty
web_1            |     self.__mark_certainty_to_delete(certainty)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/db_handler.py", line 434, in __mark_certainty_to_delete
web_1            |     certainty.deleted_by = self.__user
web_1            | AttributeError: 'NoneType' object has no attribute 'deleted_by'

```

**Comment by bug-rancher** [comment]
I assumed that if user add a certainty and then he want to revert his action, he will use a "discard" method for this operation. So, proper action in this case will be send a request:
```
{
  'method': 'discard',
  'payload': [int]  # id of certainty adding operation from WebSocket response
}
```

"DELETE" method is used to removing already saved elements. So, if user add a certainty, then save his changes, and then delete this saved certainty, everything will be ok. 

I need to consider if better way will be let user edit/delete not saved elements, or disable this possibility for all elements, not only for certainties.

For now, please:
- discard unsaved elements instead delete/modify
- delete/modify only saved elements

**Comment by bug-rancher** [comment]
Issue fixed.

I forbid to delete unsaved elements. Now server response with:
```
{
  "status": 400,
  "message": "Deleting an unsaved element is forbidden. Instead of deleting, discard the operation that created this element."
}
```
every time, when he get a request to delete unsaved element. This applies to all elements, not only to certainties.
