### ISSUE TITLE
[Annotator] Dates in entities properties are expected to be ISO format

### ISSUE THREAD

**Issue by virdiignis** [providedh/collaborative-platform#136]
Hi. While creating entity in annotator, filling up date fields, like: birth, death, is causing the following error in the server:
```
web_1            | Traceback (most recent call last):
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/consumers.py", line 174, in receive
web_1            |     self.__request_handler.modify_file(operations)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/request_handler.py", line 34, in modify_file
web_1            |     self.__add_reference_to_entity(operation)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/request_handler.py", line 218, in __add_reference_to_entity
web_1            |     entity_xml_id = self.__db_handler.add_entity(entity_type, entity_properties)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/db_handler.py", line 31, in add_entity
web_1            |     self.__create_entity_properties_objects(entity_version, entity_properties)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/db_handler.py", line 399, in __create_entity_properties_objects
web_1            |     entity_property_object.set_value(value)
web_1            |   File "/code/src/collaborative_platform/apps/api_vis/models.py", line 91, in set_value
web_1            |     self.value_date = date.fromisoformat(str(value))
web_1            | ValueError: Invalid isoformat string: '24.11.1991'
```

unless field is filled with actual ISOfromat string. There is no error dialog on the site. Besides, I don't think that requiring users to provide input in this format is reasonable.

**Comment by Janchorizo** [comment]
This could be solved by providing a time input. It is not ideal as the logic handles all properties the same way without any knowledge about the semantics of the property. What is your opinion?

**Comment by virdiignis** [comment]
I see that the iso format expected by backend is just YYYY-MM-DD, so maybe splitting date into 3 fields with feasible ranges for months and days would be sufficient?
