### ISSUE TITLE
[Annotator] Discarding entity creation causes error

### ISSUE THREAD

**Issue by virdiignis** [providedh/collaborative-platform#137]
While trying to discard entity creation in attached file, an error occurs:
```
web_1            | Send response to user: 'test' with content: '{"status": 500, "message": "Unhandled exception.", "body_content": null}'
web_1            | Traceback (most recent call last):
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/consumers.py", line 180, in receive
web_1            |     self.__request_handler.discard_changes(operations_ids)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/request_handler.py", line 77, in discard_changes
web_1            |     self.__discard_adding_tag(operation)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/request_handler.py", line 496, in __discard_adding_tag
web_1            |     body_content = self.__xml_handler.discard_adding_tag(body_content, tag_xml_id)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/xml_handler.py", line 165, in discard_adding_tag
web_1            |     text = self.__remove_tag(text, tag_xml_id)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/xml_handler.py", line 537, in __remove_tag
web_1            |     parent.text += element.text
web_1            | TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```
The above is not a case when example files are used, so it may be my error in file construction. If so — please point it out, I'm trying to create files for tests of NNDisambiguator.

[music.zip](https://github.com/providedh/collaborative-platform/files/5149946/music.zip)

**Comment by bug-rancher** [comment]
I tried to replicate this issue, but everything looks ok. Maybe cause of this issue was fixed during last modifications. Please try to replicate this issue on `develop` branch, with latest changes, latest migrations and fresh database and let me know if this issue still exist.
