### ISSUE TITLE
[Annotator] Cannot edit date when parameter

### ISSUE THREAD

**Issue by virdiignis** [providedh/collaborative-platform#143]
Trying to edit value of _when_ parameter of the **date** entity (cannot check for time atm) results in the error in the backend.
Log:
```
None - - [02/Sep/2020:09:33:41] "WSCONNECTING /ws/close_reading/2_3/" - -
2020-09-02 09:33:41,878 - INFO - User with id: '1' was added to room group: 'close_reading_2_3'
2020-09-02 09:33:41,878 INFO     User with id: '1' was added to room group: 'close_reading_2_3'
2020-09-02 09:33:41,921 - INFO - User with id: '1' was added to 'room_presence' table
2020-09-02 09:33:41,921 INFO     User with id: '1' was added to 'room_presence' table
None - - [02/Sep/2020:09:33:41] "WSCONNECT /ws/close_reading/2_3/" - -
2020-09-02 09:33:41,955 - INFO - Content of <body> element of file with id: 3 in version: 2 was loaded to room 2_3
2020-09-02 09:33:41,955 INFO     Content of <body> element of file with id: 3 in version: 2 was loaded to room 2_3
2020-09-02 09:34:06,072 - INFO - Got request from user with id: '1' with content:
'{  
    "method": "modify",
    "payload": [
        {   
            "element_type": "tag",
            "method": "POST",
            "parameters": {
                "end_pos": 1073,
                "start_pos": 1069
            }
        },
        {   
            "edited_element_id": 0,
            "element_type": "reference",
            "method": "POST",
            "parameters": {
                "entity_properties": {
                    "name": "Vodka",
                    "when": "1090-01-01"
                },
                "entity_type": "date"
            }
        }
    ]
}'
2020-09-02 09:34:06,072 INFO     Got request from user with id: '1' with content:
'{  
    "method": "modify",
    "payload": [
        {   
            "element_type": "tag",
            "method": "POST",
            "parameters": {
                "end_pos": 1073,
                "start_pos": 1069
            }
        },
        {   
            "edited_element_id": 0,
            "element_type": "reference",
            "method": "POST",
            "parameters": {
                "entity_properties": {
                    "name": "Vodka",
                    "when": "1090-01-01"
                },
                "entity_type": "date"
            }
        }
    ]
}'
2020-09-02 09:34:06,819 - INFO - Content of file with id: '3' updated with request from user with id: '1' was sent to users with ids: 1
2020-09-02 09:34:06,819 INFO     Content of file with id: '3' updated with request from user with id: '1' was sent to users with ids: 1
2020-09-02 09:34:09,161 - INFO - Got request from user with id: '1' with content:
'{  
    "method": "save",
    "payload": [
        10,
        11
    ]
}'
2020-09-02 09:34:09,161 INFO     Got request from user with id: '1' with content:
'{  
    "method": "save",
    "payload": [
        10,
        11
    ]
}'
2020-09-02 09:34:10,413 - INFO - Content of file with id: '3' updated with request from user with id: '1' was sent to users with ids: 1
2020-09-02 09:34:10,413 INFO     Content of file with id: '3' updated with request from user with id: '1' was sent to users with ids: 1
2020-09-02 09:34:22,157 - INFO - Got request from user with id: '1' with content:
'{  
    "method": "modify",
    "payload": [
        {   
            "edited_element_id": "date-0",
            "element_type": "entity_property",
            "method": "PUT",
            "old_element_id": "when",
            "parameters": {
                "when": "1900-01-01"
            }
        }
    ]
}'
2020-09-02 09:34:22,157 INFO     Got request from user with id: '1' with content:
'{  
    "method": "modify",
    "payload": [
        {   
            "edited_element_id": "date-0",
            "element_type": "entity_property",
            "method": "PUT",
            "old_element_id": "when",
            "parameters": {
                "when": "1900-01-01"
            }
        }
    ]
}'
2020-09-02 09:34:22,179 - ERROR - Request from user with id: 1 caused unhandled exception: get() returned more than one EntityProperty -- it returned 2!
Traceback (most recent call last):
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/consumers.py", line 169, in receive
    self.__request_handler.modify_file(operations)
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/request_handler.py", line 48, in modify_file
    element_saved = self.__modify_entity_property(operation)
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/request_handler.py", line 468, in __modify_entity_property
    old_property_value = self.__db_handler.get_entity_property_value(entity_xml_id, property_name)
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/db_handler.py", line 351, in get_entity_property_value
    entity_property = self.__get_entity_property_from_db(entity_xml_id, property_name, saved=False)
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/db_handler.py", line 656, in __get_entity_property_from_db
    entity_property = EntityProperty.objects.get(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/query.py", line 410, in get
    raise self.model.MultipleObjectsReturned(
apps.api_vis.models.EntityProperty.MultipleObjectsReturned: get() returned more than one EntityProperty -- it returned 2!
2020-09-02 09:34:22,179 ERROR    Request from user with id: 1 caused unhandled exception: get() returned more than one EntityProperty -- it returned 2!
Traceback (most recent call last):
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/consumers.py", line 169, in receive
    self.__request_handler.modify_file(operations)
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/request_handler.py", line 48, in modify_file
    element_saved = self.__modify_entity_property(operation)
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/request_handler.py", line 468, in __modify_entity_property
    old_property_value = self.__db_handler.get_entity_property_value(entity_xml_id, property_name)
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/db_handler.py", line 351, in get_entity_property_value
    entity_property = self.__get_entity_property_from_db(entity_xml_id, property_name, saved=False)
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/db_handler.py", line 656, in __get_entity_property_from_db
    entity_property = EntityProperty.objects.get(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/db/models/query.py", line 410, in get
    raise self.model.MultipleObjectsReturned(
apps.api_vis.models.EntityProperty.MultipleObjectsReturned: get() returned more than one EntityProperty -- it returned 2!
2020-09-02 09:34:22,183 - INFO - Send response to user with id: '1' with content:
'{  
    "body_content": null,
    "message": "Unhandled exception.",
    "status": 500
}'
2020-09-02 09:34:22,183 INFO     Send response to user with id: '1' with content:
'{  
    "body_content": null,
    "message": "Unhandled exception.",
    "status": 500
}'
```

**Comment by virdiignis** [comment]
Actually same can happen to any entity if same-type parameters of the same-type entities exist in other files. Probably getting EntityProperties in src/collaborative_platform/apps/close_reading/db_handler.py:646, 656
```
entity_property = EntityProperty.objects.get(
                    entity__xml_id=entity_xml_id,
                    name=property_name,
                    entity_version__isnull=True
                )
```
without specifying file or something unique for file wasn't the best idea.
