### ISSUE TITLE
Alex's error on the annotator

### ISSUE THREAD

**Issue by virdiignis** [providedh/collaborative-platform#175]
Hello guys, here are the logs from the backend from today's annotating on the call. I have also packed whole logs folder available to download here: https://providedh-test.ehum.psnc.pl/static/logs.zip 
Let's debug it together, to hopefully make annotator working as expected in all cases and for everyone.

Just to remind you, the file on which we were working on during the call was: https://providedh-test.ehum.psnc.pl/close_reading/project/3/file/7/

Error message along with some context:
```
2020-11-18 09:49:12,494 - INFO - Got request from user with id: '5' with content:
'{
    "method": "modify",
    "payload": [
        {
            "element_type": "tag",
            "method": "POST",
            "parameters": {
                "end_pos": 1855,
                "start_pos": 1850
            }
        },
        {
            "element_type": "certainty",
            "method": "POST",
            "new_element_id": 0,
            "parameters": {
                "asserted_value": "bla bla",
                "categories": [
                    "imprecision"
                ],
                "certainty": "medium",
                "description": "",
                "locus": "value"
            }
        }
    ]
}'
2020-11-18 09:49:13,110 - INFO - Content of file with id: '7' updated with request from user with id: '5' was sent to users with ids: 5, 2
2020-11-18 09:49:27,974 - INFO - User with id: '3' was added to room group: 'close_reading_3_7'
2020-11-18 09:49:28,002 - INFO - User with id: '3' was added to 'room_presence' table
2020-11-18 09:49:32,073 - INFO - User with id: '3' was removed from 'room_presence' table
2020-11-18 09:49:32,078 - INFO - In room: '3_7' left: 2 users
2020-11-18 09:49:32,081 - INFO - File with id: 7 have: 9 pending operations
2020-11-18 09:49:32,235 - INFO - User with id: '3' was added to room group: 'close_reading_3_7'
2020-11-18 09:49:32,261 - INFO - User with id: '3' was added to 'room_presence' table
2020-11-18 09:49:33,836 - INFO - Got request from user with id: '5' with content:
'{
    "method": "modify",
    "payload": [
        {
            "element_type": "tag",
            "method": "POST",
            "parameters": {
                "end_pos": 1855,
                "start_pos": 1850
            }
        },
        {
            "element_type": "certainty",
            "method": "POST",
            "new_element_id": 0,
            "parameters": {
                "asserted_value": "bla bla",
                "categories": [
                    "imprecision"
                ],
                "certainty": "medium",
                "description": "",
                "locus": "value"
            }
        }
    ]
}'
2020-11-18 09:49:33,869 - ERROR - Request from user with id: 5 caused unhandled exception: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/consumers.py", line 169, in receive
    self.__request_handler.modify_file(operations)
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/request_handler.py", line 27, in modify_file
    self.__add_tag(operation)
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/request_handler.py", line 180, in __add_tag
    body_content = self.__xml_handler.add_tag(body_content, start_pos, end_pos, tag_xml_id)
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/xml_handler.py", line 21, in add_tag
    text = self.__add_tag(text, start_pos, end_pos, tag_xml_id)
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/xml_handler.py", line 621, in __add_tag
    text_in_parts = TextSplitter().split_text_to_autonomic_parts(text_inside)
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/text_splitter.py", line 6, in split_text_to_autonomic_parts
    parts = self.split(text)
  File "/home/ubuntu/collaborative-platform/src/collaborative_platform/apps/close_reading/text_splitter.py", line 25, in split
    part = tag.group()
AttributeError: 'NoneType' object has no attribute 'group'
2020-11-18 09:49:33,871 - INFO - Send response to user with id: '5' with content:
'{
    "body_content": null,
    "message": "Unhandled exception.",
    "status": 500
}'
```

**Comment by bug-rancher** [comment]
Hi, I tried to replicate this issue basing on the video, but everything works fine. Sometimes backend's issues are caused  by invalid positions in the request (e.g. when positions point to a fragment that begin in the middle of the tag, or `start_pos` and `end_pos` are equal). I added validation for positions in the requests and now, if positions are incorrect I return a message with the code 400 and an error description. I hope that helps to identify this cases.
