### ISSUE TITLE
The annotator fails to annotate 

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#184]
Branch: `tei_format_updates` (from clean rebuild)
Expected result: An annotation being created
Steps to reproduce: Open a file in the annotator, select a piece of text and make any kind of annotation.
Logs: [logs.zip](https://github.com/providedh/collaborative-platform/files/5614596/logs.zip)

Sample error:
```
web_1            | 2020-11-30 08:12:45,966 - ERROR - Request from user with id: 2 caused unhandled exception: FileMaxXmlIds matching query does not exist.
web_1            | Traceback (most recent call last):
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/consumers.py", line 172, in receive
web_1            |     self.__request_handler.modify_file(operations)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/request_handler.py", line 27, in modify_file
web_1            |     self.__add_tag(operation)
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/request_handler.py", line 177, in __add_tag
web_1            |     tag_xml_id = self.__db_handler.get_next_xml_id('seg')
web_1            |   File "/code/src/collaborative_platform/apps/close_reading/db_handler.py", line 382, in get_next_xml_id
web_1            |     entity_max_xml_id = FileMaxXmlIds.objects.get(
web_1            |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
web_1            |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1            |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
web_1            |     raise self.model.DoesNotExist(
web_1            | apps.files_management.models.FileMaxXmlIds.DoesNotExist: FileMaxXmlIds matching query does not exist.
```

Sample request:
```
web_1            | '{
web_1            |     "method": "modify",
web_1            |     "payload": [
web_1            |         {
web_1            |             "element_type": "tag",
web_1            |             "method": "POST",
web_1            |             "parameters": {
web_1            |                 "end_pos": 908,
web_1            |                 "start_pos": 900
web_1            |             }
web_1            |         },
web_1            |         {
web_1            |             "element_type": "certainty",
web_1            |             "method": "POST",
web_1            |             "new_element_id": 0,
web_1            |             "parameters": {
web_1            |                 "asserted_value": "revisited",
web_1            |                 "categories": [
web_1            |                     "imprecision"
web_1            |                 ],
web_1            |                 "certainty": "medium",
web_1            |                 "description": "",
web_1            |                 "locus": "value"
web_1            |             }
web_1            |         }
web_1            |     ]
web_1            | }'
```

**Comment by bug-rancher** [comment]
I forgot to update `settings_template.py` file. Please pull last changes, update your local `settings.py` file, upload fresh file, and try annotate again, it should be ok.

Because we had to update format of out files according to reviewers suggestions, I updated sample files in: https://drive.google.com/drive/folders/1PhsbbNRjq8nCBgHLRgq3xyA9PhsLugjw , so you can use this files.
