### ISSUE TITLE
Error when retrieving entities in a file/project

### ISSUE THREAD

**Issue by Janchorizo** [providedh/collaborative-platform#71]
After some work with the platform (uploading and annotating), the server returns an HTTP 500 
response for the following api endpoints:
- /api/vis/projects/<id>/entities/
- /api/vis/projects/<id>/files/<id>/entities/
- /api/vis/projects/<id>/unbouned_entities/
- /api/vis/projects/<id>/files/<id>/unbounded_entities/

The following error shows in the server logs:
```
Internal Server Error: /api/vis/projects/2/files/37/entities/
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
     response = get_response(request)
   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
     response = self.process_exception_by_middleware(e, request)
   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
     return view_func(request, *args, **kwargs)
   File "/code/src/collaborative_platform/apps/views_decorators.py", line 97, in decorator
     return view(*args, **kwargs)
   File "/code/src/collaborative_platform/apps/views_decorators.py", line 120, in inner
     return func(request, *args, **kwargs)
   File "/code/src/collaborative_platform/apps/api_vis/api.py", line 993, in file_entities
     entities = common_filter_entities(query_string, project_id)
   File "/code/src/collaborative_platform/apps/api_vis/helpers.py", line 620, in common_filter_entities
     'name': ENTITY_CLASSES[entity.type].objects.get(entity_id=entity.id).name,
   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
     return getattr(self.get_queryset(), name)(*args, **kwargs)
   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 410, in get
     raise self.model.MultipleObjectsReturned(
 apps.api_vis.models.ObjectVersion.MultipleObjectsReturned: get() returned more than one ObjectVersion -- it returned 2!
```

**Comment by virdiignis** [comment]
Fixed. But I changed unbounded to unbound, like it was stated in API desing in the beginning.
